name: 🛠️ Manual Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "::notice::🛠️ Installing stuff.!"
          
          apt-get update && apt-get install -y --no-install-recommends \
          bash git curl wget unzip tzdata openssl ca-certificates \
          && rm -rf /var/lib/apt/lists/*

          echo "::notice::✅ Stuff installed succesfully."
          
